
usr/lib/llvm-5.0/bin/count
usr/lib/llvm-5.0/bin/FileCheck
usr/lib/llvm-5.0/bin/not
usr/lib/llvm-5.0/share/opt-viewer/opt-viewer.py
usr/lib/llvm-5.0/share/opt-viewer/optrecord.py
usr/lib/llvm-5.0/share/opt-viewer/style.css
usr/lib/llvm-5.0/share/opt-viewer/opt-diff.py
usr/lib/llvm-5.0/share/opt-viewer/optpmap.py
usr/lib/llvm-5.0/share/opt-viewer/opt-stats.py

utils/lit/*             /usr/lib/llvm-5.0/build/utils/lit/

usr/bin/count-5.0
usr/bin/FileCheck-5.0
usr/bin/not-5.0

