usr/lib/llvm-5.0/lib/libLLVM*.a
#usr/lib/llvm-5.0/lib/libllvm*.a
usr/lib/llvm-5.0/lib/LLVM*.so
usr/lib/llvm-5.0/lib/libLLVM.so
usr/lib/llvm-5.0/lib/libLLVM-5.0.so
usr/lib/llvm-5.0/lib/libLLVM-5.0.1.so
usr/lib/llvm-5.0/lib/libLTO.*
usr/lib/llvm-5.0/lib/BugpointPasses.so
usr/lib/llvm-5.0/include/llvm/      usr/include/llvm-5.0/
usr/lib/llvm-5.0/include/llvm-c/	usr/include/llvm-c-5.0/
# Explicit debian/tmp since there are multiple declarations
debian/tmp/usr/lib/llvm-5.0/lib/cmake/llvm/*.cmake

utils/vim/indent/llvm-5.0.vim		        usr/share/vim/addons/indent/

utils/vim/syntax/llvm-5.0.vim		        usr/share/vim/addons/syntax/
utils/vim/syntax/tablegen-5.0.vim		    usr/share/vim/addons/syntax/

utils/vim/ftdetect/llvm-5.0.vim		        usr/share/vim/addons/ftdetect/
utils/vim/ftdetect/tablegen-5.0.vim		    usr/share/vim/addons/ftdetect/

utils/vim/ftplugin/llvm-5.0.vim		        usr/share/vim/addons/ftplugin/
utils/vim/ftplugin/tablegen-5.0.vim		    usr/share/vim/addons/ftplugin/

utils/vim/llvm-5.0-vimrc		            usr/share/vim/addons


utils/emacs/emacs.el		    usr/share/emacs/site-lisp/llvm-5.0/
utils/emacs/llvm-mode.el	    usr/share/emacs/site-lisp/llvm-5.0/
utils/emacs/tablegen-mode.el	usr/share/emacs/site-lisp/llvm-5.0/

